export const pokemonTypeMap: Record<string, string> = {
  inseto: 'bug',
  noturno: 'dark',
  dragão: 'dragon',
  elétrico: 'electric',
  fada: 'fairy',
  lutador: 'fighting',
  fogo: 'fire',
  voador: 'flying',
  fantasma: 'ghost',
  grama: 'grass',
  terrestre: 'ground',
  gelo: 'ice',
  normal: 'normal',
  venenoso: 'poison',
  psíquico: 'psychic',
  pedra: 'rock',
  metálico: 'steel',
  água: 'water',
};